name: Python CI
on:
  pull_request: {}
  push:
    branches: 
        - "main" 
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"] # it will make sense to add more versions if we run tests.
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black ruff pyupgrade
    - name: Lint
      run: |
        black --check src/
        ruff check src/
        find . -type f -name "*.py" | xargs pyupgrade --py39-plus